#-------------------------------
# Site Settings

title: EmaSato.Dev
tab__title: EmaSato.Dev¬°Todos podemos programar! Programaci√≥n y tecnolog√≠a
meta__title: Ingeniero de software en DEPT‚Ñ¢. Art√≠culos, v√≠deos, recursos y tutoriales sobre  programaci√≥n, Frontend, JavaScript ‚òïÔ∏è, React ‚öõÔ∏è, CSS y tecnolog√≠a
logo: #'/assets/img/logo.webp'
description: Ingeniero de software en DEPT‚Ñ¢. Art√≠culos, v√≠deos, recursos y tutoriales sobre  programaci√≥n, Frontend, JavaScript ‚òïÔ∏è, React ‚öõÔ∏è, CSS y tecnolog√≠a

menu__settings:
  menu__items:
    - title: 'Proyectos'
      url: '/projects/'
    - title: 'Blog'
      url: '/blog/'
    - title: 'Curriculum'
      url: '/curriculum'
    - title: 'Links'
      url: '/links'
    - title: 'Cursos'
      submenu:
        - title: 'JavaScript'
          url: '/javascript'



# Call to action button
cta__button__text: Mi Curriculum
cta__button_url: '/cv/curriculum-fabian-gonzalez.pdf'

# Add global cover image (This field adds a background to the top and bottom of the site.)
cover__image: '/assets/img/background.svg'


#-------------------------------
# Author Settings

author:
  name: EmaSato Dev
  title: üëã ¬°Hola Mundo! Soy EmaSato.Dev
  # bio: Art Director & Graphic Designer based in Australia, crafting beautiful and functional websites and mobile apps. When I‚Äôm not working, I‚Äôm probably listening to relaxing music or traveling somewhere.
  bio: "
<b>Ingeniero de Software üñ•Ô∏è</b> Experto en AEM, HTML, CSS, JS, PHP, MySQL, ReactJS. Apasionado por la tecnolog√≠a y el desarrollo web ü§ì"
  image: '/assets/img/600x600.webp'
  imageMobile: '/assets/img/avatar.png'
  avatar: '/assets/img/sato-avatar.webp'
  button__text: Agenda reuni√≥n laboral üìÖ
  button__text2: Descarga mi curriculum üìù


#-------------------------------
# Projects Settings

projects__settings:
  projects__title: √öltimos <span class="text-span">Trabajos</span> # Add a 'text-span' class to highlight text.
  projects__description: "Mis √∫ltimos trabajos de desarrollo web y dise√±o:"


#-------------------------------
# Testimonials Section

testimonial__title: Mis  <span class="text-span">Clientes</span> # Add a 'text-span' class to highlight text.

testimonial-items:
  - name: "Levi Robertson"
    image: "/assets/img/testimonial-levi.jpeg"
    designation : "Host of JAMstack Phoenix"
    content : "The Angular Tutorial along with Fabian‚Äôs advice has completely changed my career..."

  - name: "Kaeside Iwuagwu"
    image: "/assets/img/testimonial-kaeside.jpeg"
    designation : "Implementation Manager at WebMD"
    content : "Fabian has a knack for breaking down complex topics and keeps learning Angular fun."

  - name: "Matthew Knowles"
    image: "/assets/img/testimonial-matthew.jpeg"
    designation : "Software Engineer"
    content : "If you are using Angular in a professional setting I can not recommend The Angular Tutorial highly enough."

#-------------------------------
# Blog Section

blog__settings:
  blog__title: Posteos recientes del <span class="text-span">Blog</span> # Add a 'text-span' class to highlight text.
  blog__description:


#-------------------------------
# Contact Settings

contact__settings:
  contact__email: fabiangonzalezdev@gmail.com # Add your email for contact form
  contact__title: Estate <span class="text-span">en contacto</span>  # Add a title to your form
  contact__description: ¬øQUieres hablar de trabajo? ¬øQUieres hablar de Webdev o dise√±o? ¬°Ac√° estoy!. # Add a description to your form

# NOTE
# Avenco comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.

#-------------------------------
# Newsletter Settings
mailchimp__settings:
  mailchimp__title: <span class="text-span">Cont√°ctate</span> Conmigo  # Add your title
  mailchimp__text: " 'Para hablar de trabajo', 'Para hablar de programaci√≥n' " # Add descriptions to the form by wrapping the text in single quotes. If you want to use more than one sentence, be sure to separate them with a comma.
  mailchimp__identifier:  http://eepurl.com/hIkfHr # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/Suscribite/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
  mailchimp__button__text: Env√≠ame Whatsapp &nbsp; <i class="ion ion-logo-whatsapp"></i> # Add your button text


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: https-FabianGonzalez-github-io # add your shortname for Disqus Comment. For example anvodstudio-demo

#-------------------------------
# Google Analytics
google-analytics: G-0FJ2SRHHEC # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Footer Settings
# Social Links

social:
- {icon: "ion-logo-twitter", link: "https://x.com/emasatodev"}
- {icon: "ion-logo-github", link: "https://github.com/fabiangonzalezdev"}
- {icon: "ion-logo-instagram", link: "https://www.instagram.com/emasato.dev/"}
- {icon: "ion-logo-youtube", link: "https://www.youtube.com/@emasatodev"}
- {icon: "ion-logo-tiktok", link: "https://www.tiktok.com/@emasatodev"}